main: revert tar change

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -16,7 +16,13 @@ release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.zip"
 # Download tar.gz file to the download directory
 download_release "$ASDF_INSTALL_VERSION" "$release_file"
 
-tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" || fail "Could not extract $release_file"
+if ! type "unzip" &>/dev/null; then
+  echo "ERROR: Command 'unzip' not found."
+  echo "unzip must be installed on your system."
+  exit 1
+fi
+
+unzip -q "$release_file" -d "$ASDF_DOWNLOAD_PATH" || exit 1
 
 # rename the tool to an unversioned name
 mv "${ASDF_DOWNLOAD_PATH}/${TOOL_NAME}_v${ASDF_INSTALL_VERSION}" "${ASDF_DOWNLOAD_PATH}/$TOOL_NAME"
